dist: bionic
language: cpp
os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9
      - libfmt-dev
env:
  global:
    - CC=gcc-9
    - CXX=g++-9

install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 291F9FF6FD385783
  - sudo apt-add-repository -y 'deb https://apt.kitware.com/ubuntu/ bionic main'
  - sudo apt-get -q update
  - sudo apt-get -y --allow-unauthenticated install cmake
  - sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"

script:
  - mkdir build && cd build
  - /usr/bin/cmake ..
  - make
